name: Worldbridger Lightcenter
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18006388121284544
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfa'
    - '#41346d'
    - '#ada3d8'
    - '#5659a1'
    - '#f69f00'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
