name: Worldbridger Lightcenter
favicon: null
layout_spectrum: 1
typography_spectrum: 0.18006388121284544
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3158076915424317
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
